### ISSUE TITLE
Not Fully Functional

### ISSUE THREAD

**Issue by Audacity01** [freireguilherme/blogProject#1]
Hey, i did the migration, and the project is up and running.
I tried registering and then logging in, and after that, there are no options to create posts, whatever. There are no other options. 
Attaching the screenshot.
![image](https://github.com/freireguilherme/blogProject/assets/64121896/7f5bbf21-ec57-43c1-b01c-ebb80aa5c1be)

**Comment by freireguilherme** [comment]
Hi audacity01,

I noticed you opened an issue on this simple repository. It seems you're not currently logged in with administrator privileges based on the attached screenshot.

Here's a breakdown of user permissions:

SuperAdmin: Can create both Admin and regular users.
Admin: Can only create regular users.
Login Credentials:

SuperAdmin: superadmin@blog.com / Superadmin@123 (Please note the capitalization difference in the password.)
I apologize that my Readme file didn't fully explain this. I'll update it to be clearer.

Let me know if you have any questions.

**Comment by Audacity01** [comment]
Thanks bruh, now it's good up and running.
